<div x-data="zemtabDemo()" class="overflow-hidden rounded-3xl border border-zem-border bg-white shadow-xl shadow-black/5">
    <div class="flex flex-wrap items-center justify-between gap-3 border-b border-zem-border bg-zem-bg px-4 py-4 sm:px-6">
        <div class="flex items-center gap-2"><span class="h-2 w-2 rounded-full bg-zem-green" aria-hidden="true"></span><span class="text-sm font-semibold">{{ __('Interactive demo') }}</span><span class="rounded-md border border-zem-border px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-zem-muted">{{ __('Sample venue') }}</span></div>
        <div class="flex items-center gap-3"><label class="sr-only" for="demo-venue">{{ __('Venue type') }}</label><select id="demo-venue" x-model="venue" @change="reset(venue)" class="rounded-lg border border-zem-border bg-white px-3 py-2 text-sm"><option value="restaurant">{{ __('Restaurant') }}</option><option value="hotel">{{ __('Hotel') }}</option></select><button type="button" @click="reset()" class="text-sm font-semibold text-zem-muted hover:text-zem-gold">{{ __('Reset') }}</button></div>
    </div>
    <noscript><p class="p-6">Enable JavaScript to try the interactive demo. You can still request a guided demo below.</p></noscript>
    <div x-cloak>
        <div class="flex flex-wrap items-center justify-between gap-3 px-4 pt-5 sm:px-6">
            <div class="flex rounded-xl bg-zem-soft p-1" aria-label="Demo views">
                <button type="button" @click="view = 'guest'" :aria-pressed="view === 'guest'" :class="view === 'guest' ? 'bg-white shadow-sm text-zem-cream' : 'text-zem-muted'" class="rounded-lg px-4 py-2.5 text-sm font-semibold">{{ __('Guest menu') }}</button>
                <button type="button" @click="view = 'staff'" :aria-pressed="view === 'staff'" :class="view === 'staff' ? 'bg-white shadow-sm text-zem-cream' : 'text-zem-muted'" class="rounded-lg px-4 py-2.5 text-sm font-semibold">{{ __('Staff view') }} <span x-show="order || request" class="ml-1 inline-block h-2 w-2 rounded-full bg-zem-gold" aria-label="Activity available"></span></button>
            </div>
            <span class="text-xs text-zem-muted">{{ __('No sign-up. No real orders or payments.') }}</span>
        </div>
        <p role="status" aria-live="polite" class="px-4 pt-4 text-sm text-zem-muted sm:px-6" x-text="message || 'Try it: add an item, send your order, then manage it as staff.'"></p>
        <div x-show="view === 'guest'" class="grid gap-6 p-4 sm:p-6 lg:grid-cols-[minmax(0,1.45fr)_minmax(260px,1fr)]">
            <div>
                <div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-semibold uppercase tracking-wider text-zem-gold">ZemTab demo cafe</p><h3 class="mt-1 font-display text-2xl font-bold" x-text="place"></h3></div><button type="button" @click="callStaff()" :disabled="!!request" class="rounded-lg border border-zem-border px-3 py-2 text-sm font-semibold disabled:opacity-50" x-text="request ? 'Request sent' : (venue === 'hotel' ? 'Call staff' : 'Call waiter')"></button></div>
                <div class="mb-4 flex gap-2" aria-label="Menu categories">@foreach(['all' => 'All', 'food' => 'Food', 'drinks' => 'Drinks'] as $value => $label)<button type="button" @click="category = '{{ $value }}'" :aria-pressed="category === '{{ $value }}'" :class="category === '{{ $value }}' ? 'bg-zem-cream text-white' : 'bg-zem-soft text-zem-muted'" class="rounded-full px-4 py-2 text-sm font-semibold">{{ __($label) }}</button>@endforeach</div>
                <div class="grid gap-3 sm:grid-cols-2">
<template x-for="item in visibleMenu" :key="item.id"><article class="overflow-hidden rounded-2xl border border-zem-border bg-white"><img :src="@js(asset('assets')).concat('/', item.image)" :alt="item.name" loading="lazy" width="360" height="180" class="h-32 w-full bg-zem-soft object-cover"><div class="p-4"><h4 class="font-semibold" x-text="item.name"></h4><p class="mt-1 min-h-[40px] text-xs leading-5 text-zem-muted" x-text="item.description"></p><div class="mt-3 flex items-center justify-between gap-2"><span class="text-sm font-bold" x-text="money(item.price)"></span><button type="button" @click="add(item.id)" :disabled="!!order || quantity(item.id) >= 10" :aria-label="'Add ' + item.name" class="rounded-lg bg-zem-gold px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">{{ __('Add') }} +</button></div></div></article></template>
                </div>
            </div>
            <aside class="self-start rounded-2xl border border-zem-border bg-zem-bg p-5">
                <h3 class="font-semibold">{{ __('Your order') }}</h3>
                <div x-show="!order">
                    <p x-show="cart.length === 0" class="py-8 text-center text-sm leading-6 text-zem-muted">{{ __('Something delicious starts here. Add an item from the menu.') }}</p>
                    <div class="mt-4 space-y-4"><template x-for="item in cart" :key="item.id"><div class="flex items-center justify-between gap-2"><div class="min-w-0"><p class="text-sm font-semibold" x-text="item.name"></p><p class="mt-1 text-xs text-zem-muted" x-text="money(item.price * item.quantity)"></p></div><div class="flex items-center gap-2"><button type="button" @click="remove(item.id)" :aria-label="'Remove one ' + item.name" class="h-9 w-9 rounded-lg border border-zem-border bg-white">−</button><span class="text-sm" x-text="item.quantity"></span><button type="button" @click="add(item.id)" :disabled="item.quantity >= 10" :aria-label="'Add one ' + item.name" class="h-9 w-9 rounded-lg border border-zem-border bg-white disabled:opacity-40">+</button></div></div></template></div>
                    <label x-show="cart.length" class="mt-5 block text-xs font-semibold">{{ __('Order note (optional)') }}<input x-model="note" maxlength="160" placeholder="e.g. No sugar in my coffee" class="mt-2 w-full rounded-lg border border-zem-border bg-white px-3 py-2 text-sm"></label>
                    <div class="mt-5 flex justify-between border-t border-zem-border pt-4 font-semibold"><span>{{ __('Total') }}</span><span x-text="money(total)"></span></div><p class="mt-2 text-xs text-zem-muted">{{ __('Illustrative menu and prices. No extra charges in this demo.') }}</p>
                    <button type="button" @click="submit()" :disabled="!cart.length" class="mt-5 w-full rounded-xl bg-zem-gold px-4 py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">{{ __('Send demo order') }} →</button>
                </div>
                <div x-show="order" class="mt-4"><span class="inline-block rounded-full bg-green-100 px-3 py-1 text-xs font-semibold text-green-800" x-text="statusLabel"></span><p class="mt-4 text-sm text-zem-muted">{{ __('Your sample order is on the staff board. Switch views to follow its progress.') }}</p><button type="button" @click="view = 'staff'" class="mt-4 text-sm font-semibold text-zem-gold">{{ __('Open staff view') }} →</button></div>
            </aside>
        </div>
        <div x-show="view === 'staff'" class="p-4 sm:p-6">
            <div class="mb-5"><p class="text-xs font-semibold uppercase tracking-wider text-zem-gold">{{ __('Behind the counter') }}</p><h3 class="mt-1 font-display text-2xl font-bold">{{ __('The work board') }}</h3><p class="mt-2 text-sm text-zem-muted">{{ __('In the real app, cashiers confirm orders, kitchen staff prepare them, and cashiers record payment.') }}</p></div>
            <div x-show="!order && !request" class="rounded-2xl border border-dashed border-zem-border py-12 text-center"><p class="font-semibold">{{ __('Ready for your first order') }}</p><p class="mt-2 text-sm text-zem-muted">{{ __('Add something from the guest menu to see it arrive here.') }}</p><button type="button" @click="view = 'guest'" class="mt-5 rounded-xl bg-zem-gold px-5 py-3 text-sm font-semibold text-white">{{ __('Open guest menu') }}</button></div>
            <template x-if="order"><article class="rounded-2xl border border-zem-border bg-zem-bg p-5"><div class="flex flex-wrap items-start justify-between gap-3"><div><h4 class="font-semibold" x-text="'Order #' + order.id + ' · ' + order.place"></h4><p class="mt-1 text-xs text-zem-muted">{{ __('Sample order · just now') }}</p></div><span class="rounded-full border border-zem-border bg-white px-3 py-1 text-xs font-semibold" x-text="statusLabel"></span></div><div class="my-5 space-y-3"><template x-for="item in order.items" :key="item.id"><p class="flex justify-between gap-3 text-sm"><span x-text="item.quantity + ' × ' + item.name"></span><span x-text="money(item.quantity * item.price)"></span></p></template><p x-show="order.note" class="text-sm text-zem-muted" x-text="'Note: ' + order.note"></p></div><div class="flex flex-wrap items-center justify-between gap-3 border-t border-zem-border pt-4"><strong x-text="money(order.total)"></strong><button type="button" x-show="nextAction" @click="advance()" class="rounded-xl bg-zem-gold px-5 py-3 text-sm font-semibold text-white" x-text="nextAction"></button><button type="button" x-show="order.status === 'paid'" @click="reset()" class="rounded-xl border border-zem-border bg-white px-5 py-3 text-sm font-semibold">{{ __('Try again') }}</button></div></article></template>
            <div x-show="request" class="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5"><p class="text-sm font-semibold" x-text="request"></p><button type="button" @click="completeRequest()" class="rounded-lg border border-amber-300 px-4 py-2 text-sm font-semibold">{{ __('Complete request') }}</button></div>
        </div>
    </div>
</div>
@once<script src="{{ asset('assets/product-demo.js') }}?v={{ substr(hash_file('sha256', public_path('assets/product-demo.js')), 0, 12) }}"></script>@endonce
