const assert = require('node:assert/strict');
const demo = require('../public/assets/product-demo.js');
const state = demo();
state.submit();
assert.equal(state.order, null, 'Empty carts cannot submit');
state.add(999);
assert.equal(state.count, 0, 'Unknown items are ignored');
state.add(1); state.add(1); state.add(3);
assert.equal(state.total, 920);
state.remove(1);
assert.equal(state.count, 2);
state.note = '<script>alert(1)</script>';
state.submit();
assert.equal(state.view, 'staff');
assert.equal(state.order.total, 500);
assert.equal(state.order.place, 'Table 7');
assert.equal(state.order.items.length, 2);
assert.equal(state.cart.length, 0);
state.advance(); assert.equal(state.order.status, 'confirmed');
state.advance(); assert.equal(state.order.status, 'preparing');
state.advance(); assert.equal(state.order.status, 'served');
state.advance(); assert.equal(state.order.status, 'paid');
state.advance(); assert.equal(state.order.status, 'paid', 'Final state is stable');
state.reset('hotel'); assert.equal(state.order, null);
assert.equal(state.place, 'Room 204');
state.callStaff(); assert(state.request.includes('Room 204'));
state.completeRequest(); assert.equal(state.request, '');
for (let i = 0; i < 20; i++) state.add(2);
assert.equal(state.count, 10, 'Quantities are bounded');
const other = demo(); assert.equal(other.count, 0, 'Each demo starts with independent state');
console.log('Demo checks passed: cart, totals, transitions, venue reset, requests, bounded quantities, isolated state.');
