@extends('layouts.dashboard', ['heading' => 'Restaurants'])

@section('content')
<form method="post" action="{{ route('admin.restaurants.store') }}" class="mb-6 grid gap-3 rounded-md border border-zem-border bg-zem-card p-4 md:grid-cols-4">@csrf<input name="name" required placeholder="Name" class="rounded-md border border-zem-border bg-zem-bg px-3 py-2"><input name="slug" required placeholder="slug" class="rounded-md border border-zem-border bg-zem-bg px-3 py-2"><input name="phone" placeholder="Phone" class="rounded-md border border-zem-border bg-zem-bg px-3 py-2"><input name="email" placeholder="Email" class="rounded-md border border-zem-border bg-zem-bg px-3 py-2"><input name="location" placeholder="Location" class="rounded-md border border-zem-border bg-zem-bg px-3 py-2"><label class="flex items-center gap-2"><input name="is_active" type="checkbox" value="1" checked> Active</label><button class="rounded-md bg-zem-gold px-4 py-2 font-bold text-white md:col-span-2">Create restaurant</button></form>
<div class="grid gap-3">
@foreach($restaurants as $restaurant)
    <form method="post" action="{{ route('admin.restaurants.update', $restaurant) }}" class="grid gap-3 rounded-md border border-zem-border bg-zem-card p-4 md:grid-cols-6">@csrf @method('PATCH')<input name="name" value="{{ $restaurant->name }}" class="rounded-md border border-zem-border bg-zem-bg px-3 py-2"><input name="slug" value="{{ $restaurant->slug }}" class="rounded-md border border-zem-border bg-zem-bg px-3 py-2"><input name="phone" value="{{ $restaurant->phone }}" class="rounded-md border border-zem-border bg-zem-bg px-3 py-2"><input name="email" value="{{ $restaurant->email }}" class="rounded-md border border-zem-border bg-zem-bg px-3 py-2"><input name="location" value="{{ $restaurant->location }}" class="rounded-md border border-zem-border bg-zem-bg px-3 py-2"><label class="flex items-center gap-2"><input name="is_active" type="checkbox" value="1" @checked($restaurant->is_active)> Active</label><button class="rounded-md bg-zem-gold px-4 py-2 font-bold text-white">Save</button><a href="{{ route('menu.show', [$restaurant->slug, 1]) }}" class="rounded-md border border-zem-border px-4 py-2 text-center">View demo</a></form>
@endforeach
</div>
@endsection
